server {
    listen 80;
    server_name student.irishof.cloud;

    root /home/joachim/develop/ai/exam-net-clone/client-student/dist;
    index index.html;

    client_max_body_size 50M;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy naar de Backend API
    location /api {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Proxy voor Foto's (nodig voor student login)
    location /photos {
        proxy_pass http://127.0.0.1:3001;
    }

    # Proxy voor WebSockets (Inleveren / Live tracking)
    location /socket.io {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
